import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      catigory: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      descripion: ' A Popular Shirt',
      quantity: 1,
    },
    {
      name: 'fit Shirt',
      slug: 'fit-shirt',
      catigory: 'Shirts',
      image: '/images/pants3.jpg',
      price: 50,
      brand: 'adidass',
      rating: 4.6,
      numReviews: 2,
      countInStock: 60,
      descripion: ' A Popular Shirt',
      quantity: 1,
    },
    {
      name: 'slim Shirt',
      slug: 'slim-shirt',
      catigory: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Poma',
      rating: 6.5,
      numReviews: 9,
      countInStock: 10,
      descripion: ' A Popular Shirt',
      quantity: 1,
    },
    {
      name: 'pant',
      slug: 'pant',
      catigory: 'pants',
      image: '/images/pants1.jpg',
      price: 50,
      brand: 'Poma',
      rating: 6.8,
      numReviews: 9,
      countInStock: 4,
      descripion: ' A Popular pant',
      quantity: 1,
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      catigory: 'pants',
      image: '/images/pants1.jpg',
      price: 38,
      brand: 'she in',
      rating: 9.5,
      numReviews: 7,
      countInStock: 40,
      descripion: ' A Popular pants',
      quantity: 1,
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      catigory: 'pants',
      image: '/images/pants3.jpg',
      price: 43,
      brand: 'clasy',
      rating: 84,
      numReviews: 78,
      countInStock: 23,
      descripion: ' A Popular pants',
      quantity: 0,
    },
  ],
};

export default data;
